// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.11.4
// source: yelp/nrtsearch/common.proto

package luceneserver

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// `JsonNullValue` is a singleton enumeration to represent the null value for the
// `JsonValue` type union.
//
//  The JSON representation for `JsonNullValue` is JSON `null`.
type JsonNullValue int32

const (
	// Null value.
	JsonNullValue_NULL_VALUE JsonNullValue = 0
)

// Enum value maps for JsonNullValue.
var (
	JsonNullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	JsonNullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x JsonNullValue) Enum() *JsonNullValue {
	p := new(JsonNullValue)
	*p = x
	return p
}

func (x JsonNullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JsonNullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_yelp_nrtsearch_common_proto_enumTypes[0].Descriptor()
}

func (JsonNullValue) Type() protoreflect.EnumType {
	return &file_yelp_nrtsearch_common_proto_enumTypes[0]
}

func (x JsonNullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JsonNullValue.Descriptor instead.
func (JsonNullValue) EnumDescriptor() ([]byte, []int) {
	return file_yelp_nrtsearch_common_proto_rawDescGZIP(), []int{0}
}

// Modified version of google.protobuf.Struct with better support
// for long integer values.
type JsonStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unordered map of dynamically typed values.
	Fields map[string]*JsonValue `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *JsonStruct) Reset() {
	*x = JsonStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelp_nrtsearch_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonStruct) ProtoMessage() {}

func (x *JsonStruct) ProtoReflect() protoreflect.Message {
	mi := &file_yelp_nrtsearch_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonStruct.ProtoReflect.Descriptor instead.
func (*JsonStruct) Descriptor() ([]byte, []int) {
	return file_yelp_nrtsearch_common_proto_rawDescGZIP(), []int{0}
}

func (x *JsonStruct) GetFields() map[string]*JsonValue {
	if x != nil {
		return x.Fields
	}
	return nil
}

// `JsonValue` represents a dynamically typed value which can be either
// null, a number, a string, a boolean, a recursive struct value, or a
// list of values. A producer of value is expected to set one of that
// variants, absence of any variant indicates an error.
//
// The JSON representation for `JsonValue` is JSON value.
type JsonValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The kind of value.
	//
	// Types that are assignable to Kind:
	//	*JsonValue_NullValue
	//	*JsonValue_DoubleValue
	//	*JsonValue_LongValue
	//	*JsonValue_StringValue
	//	*JsonValue_BoolValue
	//	*JsonValue_StructValue
	//	*JsonValue_ListValue
	Kind isJsonValue_Kind `protobuf_oneof:"kind"`
}

func (x *JsonValue) Reset() {
	*x = JsonValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelp_nrtsearch_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonValue) ProtoMessage() {}

func (x *JsonValue) ProtoReflect() protoreflect.Message {
	mi := &file_yelp_nrtsearch_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonValue.ProtoReflect.Descriptor instead.
func (*JsonValue) Descriptor() ([]byte, []int) {
	return file_yelp_nrtsearch_common_proto_rawDescGZIP(), []int{1}
}

func (m *JsonValue) GetKind() isJsonValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (x *JsonValue) GetNullValue() JsonNullValue {
	if x, ok := x.GetKind().(*JsonValue_NullValue); ok {
		return x.NullValue
	}
	return JsonNullValue_NULL_VALUE
}

func (x *JsonValue) GetDoubleValue() float64 {
	if x, ok := x.GetKind().(*JsonValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *JsonValue) GetLongValue() int64 {
	if x, ok := x.GetKind().(*JsonValue_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (x *JsonValue) GetStringValue() string {
	if x, ok := x.GetKind().(*JsonValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *JsonValue) GetBoolValue() bool {
	if x, ok := x.GetKind().(*JsonValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

func (x *JsonValue) GetStructValue() *JsonStruct {
	if x, ok := x.GetKind().(*JsonValue_StructValue); ok {
		return x.StructValue
	}
	return nil
}

func (x *JsonValue) GetListValue() *JsonListValue {
	if x, ok := x.GetKind().(*JsonValue_ListValue); ok {
		return x.ListValue
	}
	return nil
}

type isJsonValue_Kind interface {
	isJsonValue_Kind()
}

type JsonValue_NullValue struct {
	// Represents a null value.
	NullValue JsonNullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=luceneserver.JsonNullValue,oneof"`
}

type JsonValue_DoubleValue struct {
	// Represents a double value.
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type JsonValue_LongValue struct {
	// Represents a long value.
	LongValue int64 `protobuf:"varint,3,opt,name=long_value,json=longValue,proto3,oneof"`
}

type JsonValue_StringValue struct {
	// Represents a string value.
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type JsonValue_BoolValue struct {
	// Represents a boolean value.
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type JsonValue_StructValue struct {
	// Represents a structured value.
	StructValue *JsonStruct `protobuf:"bytes,6,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type JsonValue_ListValue struct {
	// Represents a repeated `Value`.
	ListValue *JsonListValue `protobuf:"bytes,7,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*JsonValue_NullValue) isJsonValue_Kind() {}

func (*JsonValue_DoubleValue) isJsonValue_Kind() {}

func (*JsonValue_LongValue) isJsonValue_Kind() {}

func (*JsonValue_StringValue) isJsonValue_Kind() {}

func (*JsonValue_BoolValue) isJsonValue_Kind() {}

func (*JsonValue_StructValue) isJsonValue_Kind() {}

func (*JsonValue_ListValue) isJsonValue_Kind() {}

// `JsonListValue` is a wrapper around a repeated field of values.
//
// The JSON representation for `JsonListValue` is JSON array.
type JsonListValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Repeated field of dynamically typed values.
	Values []*JsonValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *JsonListValue) Reset() {
	*x = JsonListValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yelp_nrtsearch_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JsonListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonListValue) ProtoMessage() {}

func (x *JsonListValue) ProtoReflect() protoreflect.Message {
	mi := &file_yelp_nrtsearch_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonListValue.ProtoReflect.Descriptor instead.
func (*JsonListValue) Descriptor() ([]byte, []int) {
	return file_yelp_nrtsearch_common_proto_rawDescGZIP(), []int{2}
}

func (x *JsonListValue) GetValues() []*JsonValue {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_yelp_nrtsearch_common_proto protoreflect.FileDescriptor

var file_yelp_nrtsearch_common_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x79, 0x65, 0x6c, 0x70, 0x2f, 0x6e, 0x72, 0x74, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6c,
	0x75, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x2c, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x73, 0x77, 0x61, 0x67, 0x67, 0x65, 0x72, 0x2f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x0a, 0x4a, 0x73,
	0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x3c, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6c, 0x75, 0x63, 0x65, 0x6e,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x52, 0x0a, 0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x75, 0x63, 0x65, 0x6e, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xda, 0x02, 0x0a, 0x09, 0x4a,
	0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x6e, 0x75, 0x6c, 0x6c,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x6c,
	0x75, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x73, 0x6f, 0x6e,
	0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x75, 0x6c,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b,
	0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6c,
	0x6f, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x48,
	0x00, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x75, 0x63, 0x65, 0x6e,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x75, 0x63, 0x65, 0x6e, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42,
	0x06, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x40, 0x0a, 0x0d, 0x4a, 0x73, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x75, 0x63, 0x65, 0x6e,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4a, 0x73, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x2a, 0x1f, 0x0a, 0x0d, 0x4a, 0x73, 0x6f,
	0x6e, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x55,
	0x4c, 0x4c, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x00, 0x42, 0x35, 0x0a, 0x1e, 0x63, 0x6f,
	0x6d, 0x2e, 0x79, 0x65, 0x6c, 0x70, 0x2e, 0x6e, 0x72, 0x74, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x0b, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0xa2, 0x02, 0x03, 0x48, 0x4c,
	0x57, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yelp_nrtsearch_common_proto_rawDescOnce sync.Once
	file_yelp_nrtsearch_common_proto_rawDescData = file_yelp_nrtsearch_common_proto_rawDesc
)

func file_yelp_nrtsearch_common_proto_rawDescGZIP() []byte {
	file_yelp_nrtsearch_common_proto_rawDescOnce.Do(func() {
		file_yelp_nrtsearch_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_yelp_nrtsearch_common_proto_rawDescData)
	})
	return file_yelp_nrtsearch_common_proto_rawDescData
}

var file_yelp_nrtsearch_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yelp_nrtsearch_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yelp_nrtsearch_common_proto_goTypes = []interface{}{
	(JsonNullValue)(0),    // 0: luceneserver.JsonNullValue
	(*JsonStruct)(nil),    // 1: luceneserver.JsonStruct
	(*JsonValue)(nil),     // 2: luceneserver.JsonValue
	(*JsonListValue)(nil), // 3: luceneserver.JsonListValue
	nil,                   // 4: luceneserver.JsonStruct.FieldsEntry
}
var file_yelp_nrtsearch_common_proto_depIdxs = []int32{
	4, // 0: luceneserver.JsonStruct.fields:type_name -> luceneserver.JsonStruct.FieldsEntry
	0, // 1: luceneserver.JsonValue.null_value:type_name -> luceneserver.JsonNullValue
	1, // 2: luceneserver.JsonValue.struct_value:type_name -> luceneserver.JsonStruct
	3, // 3: luceneserver.JsonValue.list_value:type_name -> luceneserver.JsonListValue
	2, // 4: luceneserver.JsonListValue.values:type_name -> luceneserver.JsonValue
	2, // 5: luceneserver.JsonStruct.FieldsEntry.value:type_name -> luceneserver.JsonValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_yelp_nrtsearch_common_proto_init() }
func file_yelp_nrtsearch_common_proto_init() {
	if File_yelp_nrtsearch_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yelp_nrtsearch_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelp_nrtsearch_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yelp_nrtsearch_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JsonListValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_yelp_nrtsearch_common_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*JsonValue_NullValue)(nil),
		(*JsonValue_DoubleValue)(nil),
		(*JsonValue_LongValue)(nil),
		(*JsonValue_StringValue)(nil),
		(*JsonValue_BoolValue)(nil),
		(*JsonValue_StructValue)(nil),
		(*JsonValue_ListValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yelp_nrtsearch_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yelp_nrtsearch_common_proto_goTypes,
		DependencyIndexes: file_yelp_nrtsearch_common_proto_depIdxs,
		EnumInfos:         file_yelp_nrtsearch_common_proto_enumTypes,
		MessageInfos:      file_yelp_nrtsearch_common_proto_msgTypes,
	}.Build()
	File_yelp_nrtsearch_common_proto = out.File
	file_yelp_nrtsearch_common_proto_rawDesc = nil
	file_yelp_nrtsearch_common_proto_goTypes = nil
	file_yelp_nrtsearch_common_proto_depIdxs = nil
}
